# Configuracion global del proyecto (Gradle + Android + Kotlin)
org.gradle.jvmargs=-Xmx3072m -XX:MaxMetaspaceSize=768m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=false

# AndroidX
android.useAndroidX=true
android.nonTransitiveRClass=true
android.defaults.buildfeatures.buildconfig=true

# Kotlin
kotlin.code.style=official

# KSP es mas rapido que kapt para Room/Hilt
ksp.incremental=true
